{
 "title": "Tensorflow Serving TextClassification Model",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Model Request Rate (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "targets": [
    {
     "expr": "avg(sum by() (rate(:tensorflow:serving:request_count[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Request Latency 95th Percentil (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(:tensorflow:serving:request_latency_bucket[$__interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model predict runtime latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(rate(:tensorflow:serving:runtime_latency_sum[$__interval])) / sum(rate(:tensorflow:serving:request_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graph Runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(:tensorflow:core:graph_runs[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(:tensorflow:serving:request_count) by (status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}